<a href="https://colab.research.google.com/github/Yihong-Z/DataTidying/blob/main/Matrix0506.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Read in data

In [1]:
import pandas as pd
import numpy as np

In [2]:
carbon=pd.read_csv("/content/Biochar carbon stock 100 year_1km_pature_lower_yr2.csv")
df=pd.read_csv("/content/Dead tree_pasture_1km_lower.csv")
row=pd.read_csv("/content/Row1.csv")

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [3]:
row.head()

   Carbon stock
0    516.077809
1    213.498891
2    212.999796
3    212.615905
4    212.253905

In [4]:
row_matrix=np.array(row.transpose())

In [5]:
df.head()

,pointid,SI,1,2,3,4,5,6,7,8,...,91,92,93,94,95,96,97,98,99,100
0,1.0,100.0,0,0.000808,0.004633,0.022418,0.066473,0.152868,0.299574,0.368845,...,2.273333,2.402403,2.518093,3.295817,3.404649,3.495997,3.570239,3.627979,4.506800,4.538685
1,6.0,100.0,0,0.000808,0.004633,0.022418,0.066473,0.152868,0.299574,0.368845,...,2.273333,2.402403,2.518093,3.295817,3.404649,3.495997,3.570239,3.627979,4.506800,4.538685
2,12.0,79.0,0,0.000709,0.006546,0.009268,0.040315,0.110476,0.240183,0.294589,...,2.217918,2.361950,2.495736,2.618450,3.539014,3.665680,3.776629,3.871908,3.951763,4.016610
3,17.0,98.0,0,0.004866,0.029183,0.140289,0.414871,0.952972,1.866733,2.297738,...,14.214576,15.031839,15.766964,16.416736,21.354697,21.944376,22.427703,22.808132,23.090237,28.583556
4,18.0,77.0,0,0.000163,0.001580,0.002226,0.009612,0.026260,0.057013,0.069874,...,0.527322,0.561928,0.594173,0.623852,0.650820,0.875005,0.902228,0.925766,0.945665,0.962010

In [6]:
#DROP MULTIPLE COLUMNS: dataframe.drop(columns=['column_name_1', 'column_name_2'])
#df.iloc[:,0:3]
df_base=df.drop(columns=["pointid","SI","1"])

In [7]:
df_base=df_base.drop([11710])

In [12]:
df_base.shape

(11710, 99)

In [13]:
df_base

,2,3,4,5,6,7,8,9,10,11,...,91,92,93,94,95,96,97,98,99,100
0,0.000808,0.004633,0.022418,0.066473,0.152868,0.299574,0.368845,0.627373,0.731353,0.835483,...,2.273333,2.402403,2.518093,3.295817,3.404649,3.495997,3.570239,3.627979,4.506800,4.538685
1,0.000808,0.004633,0.022418,0.066473,0.152868,0.299574,0.368845,0.627373,0.731353,0.835483,...,2.273333,2.402403,2.518093,3.295817,3.404649,3.495997,3.570239,3.627979,4.506800,4.538685
2,0.000709,0.006546,0.009268,0.040315,0.110476,0.240183,0.294589,0.539374,0.629626,0.721382,...,2.217918,2.361950,2.495736,2.618450,3.539014,3.665680,3.776629,3.871908,3.951763,4.016610
3,0.004866,0.029183,0.140289,0.414871,0.952972,1.866733,2.297738,3.909069,4.557514,5.207814,...,14.214576,15.031839,15.766964,16.416736,21.354697,21.944376,22.427703,22.808132,23.090237,28.583556
4,0.000163,0.001580,0.002226,0.009612,0.026260,0.057013,0.069874,0.127910,0.149288,0.171051,...,0.527322,0.561928,0.594173,0.623852,0.650820,0.875005,0.902228,0.925766,0.945665,0.962010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11705,0.000275,0.001973,0.009221,0.026945,0.061565,0.078432,0.147906,0.176763,0.293638,0.335837,...,0.715148,0.983945,1.035006,1.080862,1.121357,1.156435,1.491815,1.521926,1.545653,1.563277
11706,0.000825,0.005920,0.027662,0.080836,0.184694,0.235296,0.443718,0.530289,0.880913,1.007511,...,2.145444,2.951835,3.105019,3.242587,3.364071,3.469304,4.475446,4.565777,4.636958,4.689832
11707,0.001593,0.014255,0.028222,0.115917,0.149314,0.388084,0.472458,0.964395,1.124286,1.975116,...,4.569937,4.891179,5.196103,5.482654,7.751740,8.078475,8.375417,8.641866,8.877541,9.082531
11708,0.000825,0.005920,0.027662,0.080836,0.184694,0.235296,0.443718,0.530289,0.880913,1.007511,...,2.145444,2.951835,3.105019,3.242587,3.364071,3.469304,4.475446,4.565777,4.636958,4.689832
11709,0.000677,0.005445,0.024953,0.034694,0.095855,0.209142,0.257006,0.470731,0.549640,0.895347,...,1.919341,2.039935,2.789362,2.918344,3.033507,3.134592,3.221572,3.294625,4.217811,4.274636

In [14]:
df_matrix=np.array(df_base)

In [15]:
df_matrix[:,0]

array([0.00080791, 0.00080791, 0.00070942, ..., 0.00159319, 0.00082476,
       0.00067741])

In [16]:
df_matrix_1=np.matrix(df_base.iloc[:,0]).transpose()

In [17]:
df_matrix_1

matrix([[0.00080791],
        [0.00080791],
        [0.00070942],
        ...,
        [0.00159319],
        [0.00082476],
        [0.00067741]])

In [18]:
row_matrix

array([[516.0778087, 213.4988909, 212.9997964, 212.615905 , 212.2539052,
        211.8964608, 211.5403502, 211.1849739, 210.83022  , 210.4760667,
        210.1225091, 209.7695456, 209.4171751, 209.0653965, 208.7142088,
        208.363611 , 208.0136021, 207.6641812, 207.3153473, 206.9670993,
        206.6194363, 206.2723573, 205.9258614, 205.5799474, 205.2346146,
        204.8898618, 204.5456882, 204.2020927, 203.8590743, 203.5166322,
        203.1747653, 202.8334726, 202.4927533, 202.1526063, 201.8130307,
        201.4740255, 201.1355898, 200.7977225, 200.4604229, 200.1236898,
        199.7875223, 199.4519196, 199.1168806, 198.7824044, 198.44849  ,
        198.1151366, 197.7823431, 197.4501086, 197.1184323, 196.7873131,
        196.4567501, 196.1267423, 195.797289 , 195.468389 , 195.1400415,
        194.8122456, 194.4850003, 194.1583047, 193.8321579, 193.506559 ,
        193.181507 , 192.857001 , 192.5330401, 192.2096235, 191.8867501,
        191.564419 , 191.2426294, 190.9213804, 190.6006709, 190.2805002,
        189.9608674, 189.6417714, 189.3232115, 189.0051867, 188.6876961,
        188.3707388, 188.0543139, 187.7384206, 187.4230579, 187.108225 ,
        186.7939209, 186.4801448, 186.1668957, 185.8541729, 185.5419754,
        185.2303023, 184.9191527, 184.6085258, 184.2984207, 183.9888365,
        183.6797724, 183.3712274, 183.0632007, 182.7556915, 182.4486988,
        182.1422217, 181.8362595, 181.5308113, 181.2258761, 180.9214532]])

In [19]:
#df_base.iloc[:,0]
#row_matrix.shape
#df_matrix_1[:,0].shape
df1=np.dot(df_matrix_1,row_matrix)
#row_matrix*df_matrix_1

In [20]:
pd.DataFrame(df1)

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,0.416946,0.172489,0.172085,0.171775,0.171483,0.171194,0.170906,0.170619,0.170332,0.170046,...,0.148397,0.148148,0.147899,0.147651,0.147403,0.147155,0.146908,0.146661,0.146415,0.146169
1,0.416946,0.172489,0.172085,0.171775,0.171483,0.171194,0.170906,0.170619,0.170332,0.170046,...,0.148397,0.148148,0.147899,0.147651,0.147403,0.147155,0.146908,0.146661,0.146415,0.146169
2,0.366114,0.151460,0.151105,0.150833,0.150576,0.150323,0.150070,0.149818,0.149566,0.149315,...,0.130305,0.130086,0.129868,0.129650,0.129432,0.129215,0.128998,0.128781,0.128565,0.128349
3,2.511354,1.038935,1.036506,1.034638,1.032877,1.031137,1.029404,1.027675,1.025949,1.024225,...,0.893828,0.892327,0.890828,0.889332,0.887838,0.886346,0.884857,0.883371,0.881887,0.880406
4,0.084315,0.034881,0.034799,0.034737,0.034677,0.034619,0.034561,0.034503,0.034445,0.034387,...,0.030009,0.029959,0.029908,0.029858,0.029808,0.029758,0.029708,0.029658,0.029608,0.029558
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11705,0.141881,0.058695,0.058558,0.058453,0.058353,0.058255,0.058157,0.058059,0.057962,0.057864,...,0.050497,0.050413,0.050328,0.050243,0.050159,0.050075,0.049991,0.049907,0.049823,0.049739
11706,0.425642,0.176086,0.175675,0.175358,0.175059,0.174765,0.174471,0.174178,0.173885,0.173593,...,0.151492,0.151238,0.150984,0.150730,0.150477,0.150224,0.149972,0.149720,0.149469,0.149218
11707,0.822208,0.340144,0.339349,0.338737,0.338160,0.337591,0.337023,0.336457,0.335892,0.335328,...,0.292636,0.292145,0.291654,0.291164,0.290675,0.290187,0.289699,0.289213,0.288727,0.288242
11708,0.425642,0.176086,0.175675,0.175358,0.175059,0.174765,0.174471,0.174178,0.173885,0.173593,...,0.151492,0.151238,0.150984,0.150730,0.150477,0.150224,0.149972,0.149720,0.149469,0.149218
11709,0.349595,0.144626,0.144288,0.144028,0.143782,0.143540,0.143299,0.143058,0.142818,0.142578,...,0.124426,0.124217,0.124008,0.123800,0.123592,0.123384,0.123177,0.122970,0.122764,0.122557

In [82]:
b=[]

In [ ]:
#循环生成数据框的名字/生成一个有99个位置的list
for i in range(0,99): #生成0-98的99个数字
  b.append("df"+str(i))
  print(b)

#Produce 99 dataframes

In [76]:
#Basic formula
#b[0]=np.dot(df_matrix_1,row_matrix)
#df_matrix_1=np.matrix(df_base.iloc[:,0]).transpose()

In [84]:
for i in range(0,99):
  b[i]=np.dot(np.matrix(df_base.iloc[:,i]).transpose(),row_matrix)

In [109]:
pd.DataFrame(b[0])

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,0.416946,0.172489,0.172085,0.171775,0.171483,0.171194,0.170906,0.170619,0.170332,0.170046,...,0.148397,0.148148,0.147899,0.147651,0.147403,0.147155,0.146908,0.146661,0.146415,0.146169
1,0.416946,0.172489,0.172085,0.171775,0.171483,0.171194,0.170906,0.170619,0.170332,0.170046,...,0.148397,0.148148,0.147899,0.147651,0.147403,0.147155,0.146908,0.146661,0.146415,0.146169
2,0.366114,0.151460,0.151105,0.150833,0.150576,0.150323,0.150070,0.149818,0.149566,0.149315,...,0.130305,0.130086,0.129868,0.129650,0.129432,0.129215,0.128998,0.128781,0.128565,0.128349
3,2.511354,1.038935,1.036506,1.034638,1.032877,1.031137,1.029404,1.027675,1.025949,1.024225,...,0.893828,0.892327,0.890828,0.889332,0.887838,0.886346,0.884857,0.883371,0.881887,0.880406
4,0.084315,0.034881,0.034799,0.034737,0.034677,0.034619,0.034561,0.034503,0.034445,0.034387,...,0.030009,0.029959,0.029908,0.029858,0.029808,0.029758,0.029708,0.029658,0.029608,0.029558
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11705,0.141881,0.058695,0.058558,0.058453,0.058353,0.058255,0.058157,0.058059,0.057962,0.057864,...,0.050497,0.050413,0.050328,0.050243,0.050159,0.050075,0.049991,0.049907,0.049823,0.049739
11706,0.425642,0.176086,0.175675,0.175358,0.175059,0.174765,0.174471,0.174178,0.173885,0.173593,...,0.151492,0.151238,0.150984,0.150730,0.150477,0.150224,0.149972,0.149720,0.149469,0.149218
11707,0.822208,0.340144,0.339349,0.338737,0.338160,0.337591,0.337023,0.336457,0.335892,0.335328,...,0.292636,0.292145,0.291654,0.291164,0.290675,0.290187,0.289699,0.289213,0.288727,0.288242
11708,0.425642,0.176086,0.175675,0.175358,0.175059,0.174765,0.174471,0.174178,0.173885,0.173593,...,0.151492,0.151238,0.150984,0.150730,0.150477,0.150224,0.149972,0.149720,0.149469,0.149218
11709,0.349595,0.144626,0.144288,0.144028,0.143782,0.143540,0.143299,0.143058,0.142818,0.142578,...,0.124426,0.124217,0.124008,0.123800,0.123592,0.123384,0.123177,0.122970,0.122764,0.122557

In [33]:
#Choose one column of the datafram
b[0][:,0]

matrix([[0.41694597],
        [0.41694597],
        [0.36611385],
        ...,
        [0.82220846],
        [0.4256424 ],
        [0.34959472]])

#Sum

In [ ]:
#Basic formula
b[0][:,1]+b[1][:,0]

In [107]:
b[0][:,0]

matrix([[0.41694597],
        [0.41694597],
        [0.36611385],
        ...,
        [0.82220846],
        [0.4256424 ],
        [0.34959472]])

In [ ]:
df_none=pd.DataFrame()
df_none.loc[:,0]=pd.DataFrame(b[0][:,0])
df_none

In [97]:
#Test
df_none.loc[:,0]=pd.DataFrame(b[0][:,1])
df_none.loc[:,1]=pd.DataFrame(b[1][:,0])
df_none

              0          1
0      0.172489   2.390960
1      0.172489   2.390960
2      0.151460   3.378174
3      1.038935  15.060931
4      0.034881   0.815215
...         ...        ...
11705  0.058695   1.018317
11706  0.176086   3.054951
11707  0.340144   7.356527
11708  0.176086   3.054951
11709  0.144626   2.810005

[11710 rows x 2 columns]

In [105]:
pd.DataFrame(b[0])

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,0.416946,0.172489,0.172085,0.171775,0.171483,0.171194,0.170906,0.170619,0.170332,0.170046,...,0.148397,0.148148,0.147899,0.147651,0.147403,0.147155,0.146908,0.146661,0.146415,0.146169
1,0.416946,0.172489,0.172085,0.171775,0.171483,0.171194,0.170906,0.170619,0.170332,0.170046,...,0.148397,0.148148,0.147899,0.147651,0.147403,0.147155,0.146908,0.146661,0.146415,0.146169
2,0.366114,0.151460,0.151105,0.150833,0.150576,0.150323,0.150070,0.149818,0.149566,0.149315,...,0.130305,0.130086,0.129868,0.129650,0.129432,0.129215,0.128998,0.128781,0.128565,0.128349
3,2.511354,1.038935,1.036506,1.034638,1.032877,1.031137,1.029404,1.027675,1.025949,1.024225,...,0.893828,0.892327,0.890828,0.889332,0.887838,0.886346,0.884857,0.883371,0.881887,0.880406
4,0.084315,0.034881,0.034799,0.034737,0.034677,0.034619,0.034561,0.034503,0.034445,0.034387,...,0.030009,0.029959,0.029908,0.029858,0.029808,0.029758,0.029708,0.029658,0.029608,0.029558
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11705,0.141881,0.058695,0.058558,0.058453,0.058353,0.058255,0.058157,0.058059,0.057962,0.057864,...,0.050497,0.050413,0.050328,0.050243,0.050159,0.050075,0.049991,0.049907,0.049823,0.049739
11706,0.425642,0.176086,0.175675,0.175358,0.175059,0.174765,0.174471,0.174178,0.173885,0.173593,...,0.151492,0.151238,0.150984,0.150730,0.150477,0.150224,0.149972,0.149720,0.149469,0.149218
11707,0.822208,0.340144,0.339349,0.338737,0.338160,0.337591,0.337023,0.336457,0.335892,0.335328,...,0.292636,0.292145,0.291654,0.291164,0.290675,0.290187,0.289699,0.289213,0.288727,0.288242
11708,0.425642,0.176086,0.175675,0.175358,0.175059,0.174765,0.174471,0.174178,0.173885,0.173593,...,0.151492,0.151238,0.150984,0.150730,0.150477,0.150224,0.149972,0.149720,0.149469,0.149218
11709,0.349595,0.144626,0.144288,0.144028,0.143782,0.143540,0.143299,0.143058,0.142818,0.142578,...,0.124426,0.124217,0.124008,0.123800,0.123592,0.123384,0.123177,0.122970,0.122764,0.122557

In [98]:
df_none.sum(axis=1)

0         2.563449
1         2.563449
2         3.529633
3        16.099866
4         0.850095
           ...
11705     1.077012
11706     3.231038
11707     7.696671
11708     3.231038
11709     2.954631
Length: 11710, dtype: float64

In [80]:
b[0][:,99]

matrix([[0.14616879],
        [0.14616879],
        [0.12834857],
        ...,
        [0.28824171],
        [0.1492175 ],
        [0.12255746]])

In [ ]:
summ=[]
for i in range(0,99):
  summ.append("col"+str(i))
  print(summ)

In [ ]:
for j in range(0,99): #0到98,99个数
    df_none=pd.DataFrame()
    for i in range(0,j+1): #0,...,98
        df_none.loc[:,i]=pd.DataFrame(b[i][:,j-i])
        #print(df_none)
    summ[i]=df_none.sum(axis=1) #axis=0行，axis=1列相加
    print(df_none)

In [110]:
summ

[0        0.416946
 1        0.416946
 2        0.366114
 3        2.511354
 4        0.084315
            ...
 11705    0.141881
 11706    0.425642
 11707    0.822208
 11708    0.425642
 11709    0.349595
 Length: 11710, dtype: float64, 0         2.563449
 1         2.563449
 2         3.529633
 3        16.099866
 4         0.850095
            ...
 11705     1.077012
 11706     3.231038
 11707     7.696671
 11708     3.231038
 11709     2.954631
 Length: 11710, dtype: float64, 0        12.730479
 1        12.730479
 2         6.331550
 3        79.667055
 4         1.520708
            ...
 11705     5.238498
 11706    15.715493
 11707    17.947672
 11708    15.715493
 11709    14.184703
 Length: 11710, dtype: float64, 0         40.249901
 1         40.249901
 2         24.329293
 3        251.308173
 4          5.806775
             ...
 11705     16.353338
 11706     49.060013
 11707     69.222390
 11708     49.060013
 11709     24.535991
 Length: 11710, dtype: float64, 0         99.015010
 1         99.015010
 2         69.137568
 3        617.501625
 4         16.448678
             ...
 11705     39.966899
 11706    119.900698
 11707    111.186200
 11708    119.900698
 11709     63.492007
 Length: 11710, dtype: float64, 0         207.320059
 1         207.320059
 2         159.636944
 3        1292.258630
 4          37.919793
             ...
 11705      61.797936
 11706     185.393808
 11707     266.213892
 11708     185.393808
 11709     142.392653
 Length: 11710, dtype: float64, 0         306.916032
 1         306.916032
 2         238.916741
 3        1912.538510
 4          56.711235
             ...
 11705     114.351842
 11706     343.055527
 11707     392.477909
 11708     343.055527
 11709     211.673782
 Length: 11710, dtype: float64, 0         518.842534
 1         518.842534
 2         427.956323
 3        3233.165080
 4         101.536730
             ...
 11705     160.745432
 11706     482.236297
 11707     746.916324
 11708     482.236297
 11709     376.677945
 Length: 11710, dtype: float64, 0         706.059565
 1         706.059565
 2         589.389808
 3        4399.976336
 4         139.807202
             ...
 11705     258.660693
 11706     775.982079
 11707    1034.833746
 11708     775.982079
 11709     517.635201
 Length: 11710, dtype: float64, 0         915.290462
 1         915.290462
 2         770.638432
 3        5704.546563
 4         182.785925
             ...
 11705     342.920984
 11706    1028.762953
 11707    1713.048861
 11708    1028.762953
 11709     812.927307
 Length: 11710, dtype: float64, 0        1314.401559
 1        1314.401559
 2        1148.503694
 3        8194.911041
 4         272.456139
             ...
 11705     435.909577
 11706    1307.728733
 11707    2264.125969
 11708    1307.728733
 11709    1061.422483
 Length: 11710, dtype: float64, 0         1651.798722
 1         1651.798722
 2         1460.547170
 3        10301.418834
 4          346.534578
              ...
 11705      612.691677
 11706     1838.075033
 11707     2868.504245
 11708     1838.075033
 11709     1332.541890
 Length: 11710, dtype: float64, 0         2013.903498
 1         2013.903498
 2         1797.851263
 3        12563.649830
 4          426.655480
              ...
 11705      759.963587
 11706     2279.890761
 11707     3524.726429
 11708     2279.890761
 11709     1845.837205
 Length: 11710, dtype: float64, 0         2650.396469
 1         2650.396469
 2         2434.810002
 3        16543.411120
 4          512.497419
              ...
 11705      916.952373
 11706     2750.857120
 11707     4879.442772
 11708     2750.857120
 11709     2267.586813
 Length: 11710, dtype: float64, 0         3175.747612
 1         3175.747612
 2         2952.148278
 3        19830.912311
 4          674.044821
              ...
 11705     1082.838499
 11706     3248.515496
 11707     5951.525105
 11708     3248.515496
 11709     2713.977251
 Length: 11710, dtype: float64, 0         3724.000740
 1         3724.000740
 2         3496.632331
 3        23264.320741
 4          803.750455
              ...
 11705     1372.929865
 11706     4118.789595
 11707     7086.271272
 11708     4118.789595
 11709     3182.793977
 Length: 11710, dtype: float64, 0         4292.059417
 1         4292.059417
 2         4065.750496
 3        26824.535755
 4          939.413699
              ...
 11705     1607.778016
 11706     4823.334046
 11707     8279.465251
 11708     4823.334046
 11709     4001.177035
 Length: 11710, dtype: float64, 0         5225.599826
 1         5225.599826
 2         4656.850176
 3        30492.149272
 4         1080.428128
              ...
 11705     1850.451779
 11706     5551.355337
 11707     9526.477132
 11708     5551.355337
 11709     4658.617393
 Length: 11710, dtype: float64, 0         5979.068682
 1         5979.068682
 2         5684.991132
 3        36505.797817
 4         1226.162275
              ...
 11705     2099.766392
 11706     6299.299176
 11707    11855.909227
 11708     6299.299176
 11709     5335.361906
 Length: 11710, dtype: float64, 0         6745.465059
 1         6745.465059
 2         6499.007751
 3        41323.706649
 4         1479.206343
              ...
 11705     2354.538163
 11706     7063.614490
 11707    13665.387766
 11708     7063.614490
 11709     6028.352734
 Length: 11710, dtype: float64, 0         7521.291995
 1         7521.291995
 2         7330.565609
 3        46204.328771
 4         1678.230984
              ...
 11705     2771.373887
 11706     8314.121660
 11707    15526.164179
 11708     8314.121660
 11709     6734.546295
 Length: 11710, dtype: float64, 0         8303.194680
 1         8303.194680
 2         8176.380466
 3        51127.041610
 4         1880.822631
              ...
 11705     3101.853959
 11706     9305.561878
 11707    17431.625766
 11708     9305.561878
 11709     7450.993000
 Length: 11710, dtype: float64, 0         9519.888871
 1         9519.888871
 2         9033.215486
 3        56072.185991
 4         2086.231561
              ...
 11705     3434.890841
 11706    10304.672524
 11707    19375.060312
 11708    10304.672524
 11709     8620.615098
 Length: 11710, dtype: float64, 0        10485.832951
 1        10485.832951
 2         9897.966753
 3        63758.815020
 4         2293.722442
              ...
 11705     3769.292218
 11706    11307.876654
 11707    21349.866454
 11708    11307.876654
 11709     9539.049439
 Length: 11710, dtype: float64, 0         9098.094199
 1         9098.094199
 2         8668.802231
 3        55023.739887
 4         1999.457073
              ...
 11705     3291.035682
 11706     9873.107046
 11707    18572.172464
 11708     9873.107046
 11709     8232.619319
 Length: 11710, dtype: float64, 0         9082.451560
 1         9082.451560
 2         8653.916300
 3        54929.069869
 4         1996.017432
              ...
 11705     3285.380418
 11706     9856.141255
 11707    18540.238715
 11708     9856.141255
 11709     8218.409786
 Length: 11710, dtype: float64, 0         9069.197794
 1         9069.197794
 2         8642.415373
 3        54849.509898
 4         1993.399742
              ...
 11705     3280.747061
 11706     9842.241184
 11707    18515.681164
 11708     9842.241184
 11709     8207.074520
 Length: 11710, dtype: float64, 0         9064.107902
 1         9064.107902
 2         8630.681881
 3        54820.803980
 4         1990.717569
              ...
 11705     3279.390082
 11706     9838.170246
 11707    18494.788694
 11708     9838.170246
 11709     8204.498130
 Length: 11710, dtype: float64, 0         9076.417856
 1         9076.417856
 2         8634.188030
 3        54900.460553
 4         1991.661127
              ...
 11705     3285.003284
 11706     9855.009851
 11707    18515.016052
 11708     9855.009851
 11709     8201.086662
 Length: 11710, dtype: float64, 0         9120.003099
 1         9120.003099
 2         8664.532656
 3        55174.848788
 4         1998.966998
              ...
 11705     3303.125852
 11706     9909.377557
 11707    18525.992792
 11708     9909.377557
 11709     8226.306852
 Length: 11710, dtype: float64, 0         9213.154535
 1         9213.154535
 2         8740.593349
 3        55757.959398
 4         2017.107845
              ...
 11705     3319.475381
 11706     9958.426142
 11707    18650.086976
 11708     9958.426142
 11709     8291.495453
 Length: 11710, dtype: float64, 0         9297.622491
 1         9297.622491
 2         8805.458841
 3        56286.747690
 4         2032.574644
              ...
 11705     3366.557035
 11706    10099.671104
 11707    18745.469731
 11708    10099.671104
 11709     8347.087703
 Length: 11710, dtype: float64, 0         9494.446414
 1         9494.446414
 2         8980.108354
 3        57516.036518
 4         2074.081086
              ...
 11705     3407.487574
 11706    10222.462721
 11707    19069.078809
 11708    10222.462721
 11709     8498.426005
 Length: 11710, dtype: float64, 0         9666.586239
 1         9666.586239
 2         9127.175948
 3        58591.663488
 4         2109.038081
              ...
 11705     3499.948962
 11706    10499.846885
 11707    19326.218690
 11708    10499.846885
 11709     8625.740361
 Length: 11710, dtype: float64, 0         9860.765257
 1         9860.765257
 2         9294.082812
 3        59805.202608
 4         2148.708893
              ...
 11705     3578.764543
 11706    10736.293628
 11707    19973.707966
 11708    10736.293628
 11709     8907.412486
 Length: 11710, dtype: float64, 0        10244.849760
 1        10244.849760
 2         9657.630407
 3        62204.688894
 4         2235.076753
              ...
 11705     3666.317571
 11706    10998.952713
 11707    20494.110850
 11708    10998.952713
 11709     9142.310559
 Length: 11710, dtype: float64, 0        10567.245572
 1        10567.245572
 2         9955.380265
 3        64220.471152
 4         2305.858384
              ...
 11705     3837.673237
 11706    11513.019711
 11707    21067.866427
 11708    11513.019711
 11709     9399.855704
 Length: 11710, dtype: float64, 0        10914.374194
 1        10914.374194
 2        10278.414752
 3        66392.129012
 4         2382.688017
              ...
 11705     3979.527828
 11706    11938.583483
 11707    21693.517352
 11708    11938.583483
 11709     9899.599558
 Length: 11710, dtype: float64, 0        11535.916170
 1        11535.916170
 2        10901.127854
 3        70281.469311
 4         2465.244217
              ...
 11705     4131.108396
 11706    12393.325186
 11707    23017.713791
 11708    12393.325186
 11709    10307.820469
 Length: 11710, dtype: float64, 0        12046.341431
 1        12046.341431
 2        11404.244424
 3        73478.701400
 4         2623.511398
              ...
 11705     4291.595387
 11706    12874.786160
 11707    24059.327485
 11708    12874.786160
 11709    10740.704936
 Length: 11710, dtype: float64, 0        12579.693750
 1        12579.693750
 2        11934.530660
 3        76821.992363
 4         2749.942321
              ...
 11705     4576.296689
 11706    13728.890065
 11707    25163.656196
 11708    13728.890065
 11709    11196.038379
 Length: 11710, dtype: float64, 0        13132.876649
 1        13132.876649
 2        12489.474857
 3        80292.241290
 4         2882.336355
              ...
 11705     4805.763829
 11706    14417.291486
 11707    26326.483814
 11708    14417.291486
 11709    12000.960802
 Length: 11710, dtype: float64, 0        14051.566268
 1        14051.566268
 2        13066.424379
 3        83870.039843
 4         3020.087065
              ...
 11705     5043.065621
 11706    15129.196863
 11707    27543.180343
 11708    15129.196863
 11709    12644.963136
 Length: 11710, dtype: float64, 0        14790.209280
 1        14790.209280
 2        14080.438946
 3        89794.024296
 4         3162.562977
              ...
 11705     5287.017287
 11706    15861.051860
 11707    29842.348010
 11708    15861.051860
 11709    13308.292199
 Length: 11710, dtype: float64, 0        15541.804718
 1        15541.804718
 2        14880.352906
 3        94522.419653
 4         3412.354283
              ...
 11705     5536.435119
 11706    16609.305357
 11707    31621.612959
 11708    16609.305357
 11709    13987.890112
 Length: 11710, dtype: float64, 0        16302.855577
 1        16302.855577
 2        15697.831794
 3        99313.678666
 4         3608.131624
              ...
 11705     5947.925898
 11706    17843.777692
 11707    33452.226534
 11708    17843.777692
 11709    14680.713255
 Length: 11710, dtype: float64, 0         17070.007006
 1         17070.007006
 2         16529.591331
 3        104147.178505
 4          3807.481428
              ...
 11705      6273.070003
 11706     18819.210009
 11707     35327.575952
 11708     18819.210009
 11709     15383.812002
 Length: 11710, dtype: float64, 0         18271.974720
 1         18271.974720
 2         17372.394641
 3        109003.259749
 4          4009.653960
              ...
 11705      6600.779882
 11706     19802.339645
 11707     37240.948910
 11708     19802.339645
 11709     16540.108563
 Length: 11710, dtype: float64, 0         19223.217061
 1         19223.217061
 2         18223.137769
 3        116600.975248
 4          4213.913878
              ...
 11705      6929.863203
 11706     20789.589609
 11707     39185.743962
 11708     20789.589609
 11709     17445.239753
 Length: 11710, dtype: float64, 0         17820.801265
 1         17820.801265
 2         16979.988638
 3        107777.135942
 4          3916.422975
              ...
 11705      6446.297545
 11706     19338.892636
 11707     36378.089295
 11708     19338.892636
 11709     16125.528828
 Length: 11710, dtype: float64, 0         17790.506237
 1         17790.506237
 2         16951.141590
 3        107593.850855
 4          3909.763218
              ...
 11705      6435.342078
 11706     19306.026234
 11707     36316.245195
 11708     19306.026234
 11709     16098.060798
 Length: 11710, dtype: float64, 0         17762.624695
 1         17762.624695
 2         16925.702998
 3        107425.824671
 4          3903.930821
              ...
 11705      6425.417420
 11706     19276.252261
 11707     36261.827538
 11708     19276.252261
 11709     16073.489306
 Length: 11710, dtype: float64, 0         17742.931599
 1         17742.931599
 2         16900.055253
 3        107308.801147
 4          3898.039341
              ...
 11705      6418.778029
 11706     19256.334087
 11707     36211.125121
 11708     19256.334087
 11709     16057.698926
 Length: 11710, dtype: float64, 0         17740.662880
 1         17740.662880
 2         16889.670522
 3        107300.288469
 4          3895.778983
              ...
 11705      6419.117692
 11706     19257.353076
 11707     36201.592606
 11708     19257.353076
 11709     16041.095664
 Length: 11710, dtype: float64, 0         17769.693938
 1         17769.693938
 2         16906.147602
 3        107486.655558
 4          3899.886321
              ...
 11705      6431.975581
 11706     19295.926741
 11707     36182.859464
 11708     19295.926741
 11709     16053.146220
 Length: 11710, dtype: float64, 0         17848.315638
 1         17848.315638
 2         16968.364044
 3        107981.892884
 4          3914.834006
              ...
 11705      6443.069272
 11706     19329.207816
 11707     36277.293673
 11708     19329.207816
 11709     16105.187310
 Length: 11710, dtype: float64, 0         17918.278264
 1         17918.278264
 2         17019.408541
 3        108422.955499
 4          3927.113007
              ...
 11705      6484.903919
 11706     19454.711755
 11707     36343.066275
 11708     19454.711755
 11709     16147.654133
 Length: 11710, dtype: float64, 0         18100.621224
 1         18100.621224
 2         17180.260275
 3        109564.666012
 4          3965.437007
              ...
 11705      6520.596264
 11706     19561.788790
 11707     36637.114940
 11708     19561.788790
 11709     16285.889057
 Length: 11710, dtype: float64, 0         18258.304411
 1         18258.304411
 2         17313.553267
 3        110552.861781
 4          3997.216906
              ...
 11705      6607.828257
 11706     19823.484770
 11707     36864.744063
 11708     19823.484770
 11709     16400.122046
 Length: 11710, dtype: float64, 0         18438.051076
 1         18438.051076
 2         17466.708668
 3        111679.116566
 4          4033.715958
              ...
 11705      6681.423227
 11706     20044.269681
 11707     37482.772154
 11708     20044.269681
 11709     16668.734776
 Length: 11710, dtype: float64, 0         18807.727468
 1         18807.727468
 2         17816.527899
 3        113991.465137
 4          4116.917386
              ...
 11705      6763.764415
 11706     20291.293243
 11707     37973.763340
 11708     20291.293243
 11709     16890.595394
 Length: 11710, dtype: float64, 0         19115.739372
 1         19115.739372
 2         18100.572456
 3        115920.256055
 4          4184.537905
              ...
 11705      6929.916995
 11706     20789.750984
 11707     38518.156626
 11708     20789.750984
 11709     17135.124983
 Length: 11710, dtype: float64, 0         19448.508249
 1         19448.508249
 2         18409.924662
 3        118005.068702
 4          4258.211735
              ...
 11705      7066.577240
 11706     21199.731718
 11707     39114.494582
 11708     21199.731718
 11709     17621.875144
 Length: 11710, dtype: float64, 0         20055.714600
 1         20055.714600
 2         19018.978467
 3        121807.709669
 4          4337.617433
              ...
 11705      7212.972187
 11706     21638.916559
 11707     40409.427292
 11708     21638.916559
 11709     18017.124189
 Length: 11710, dtype: float64, 0         20551.828318
 1         20551.828318
 2         19508.458685
 3        124918.388066
 4          4492.739405
              ...
 11705      7368.282268
 11706     22104.846804
 11707     41421.826416
 11708     22104.846804
 11709     18437.058580
 Length: 11710, dtype: float64, 0         21070.893134
 1         21070.893134
 2         20025.131475
 3        128175.270728
 4          4616.030401
              ...
 11705      7647.815357
 11706     22943.446069
 11707     42496.989629
 11708     22943.446069
 11709     18879.463701
 Length: 11710, dtype: float64, 0         21609.812531
 1         21609.812531
 2         20566.485094
 3        131559.256502
 4          4745.289784
              ...
 11705      7872.122965
 11706     23616.368893
 11707     43630.700742
 11708     23616.368893
 11709     19671.479519
 Length: 11710, dtype: float64, 0         22514.262606
 1         22514.262606
 2         21129.866868
 3        135050.936807
 4          4879.911108
              ...
 11705      8104.273892
 11706     24312.821676
 11707     44818.329675
 11708     24312.821676
 11709     20302.596928
 Length: 11710, dtype: float64, 0         23238.689994
 1         23238.689994
 2         22130.336478
 3        140888.947675
 4          5019.262890
              ...
 11705      8343.083345
 11706     25029.250034
 11707     47088.478576
 11708     25029.250034
 11709     20953.062710
 Length: 11710, dtype: float64, 0         23976.093689
 1         23976.093689
 2         22916.728233
 3        145531.513864
 4          5265.935315
              ...
 11705      8587.367603
 11706     25762.102807
 11707     48838.773503
 11708     25762.102807
 11709     21619.818951
 Length: 11710, dtype: float64, 0         24722.976643
 1         24722.976643
 2         23720.707630
 3        150237.087884
 4          5458.599014
              ...
 11705      8993.733430
 11706     26981.200288
 11707     50640.465720
 11708     26981.200288
 11709     22299.821992
 Length: 11710, dtype: float64, 0         25475.983966
 1         25475.983966
 2         24538.990354
 3        154985.046666
 4          5654.840406
              ...

In [111]:
result=pd.DataFrame(summ).transpose()

In [112]:
result

,0,1,2,3,4,5,6,7,8,9,...,89,90,91,92,93,94,95,96,97,98
0,0.416946,2.563449,12.730479,40.249901,99.015010,207.320059,306.916032,518.842534,706.059565,915.290462,...,28707.235796,29212.601172,29737.844141,30628.640762,31339.437632,32063.233704,32796.531894,33535.977272,34710.285477,35633.914770
1,0.416946,2.563449,12.730479,40.249901,99.015010,207.320059,306.916032,518.842534,706.059565,915.290462,...,28707.235796,29212.601172,29737.844141,30628.640762,31339.437632,32063.233704,32796.531894,33535.977272,34710.285477,35633.914770
2,0.366114,3.529633,6.331550,24.329293,69.137568,159.636944,238.916741,427.956323,589.389808,770.638432,...,27279.109615,27782.729279,28311.051698,28861.424161,29848.906314,30622.332429,31413.367965,32218.728571,33035.177294,33859.610105
3,2.511354,16.099866,79.667055,251.308173,617.501625,1292.258630,1912.538510,3233.165080,4399.976336,5704.546563,...,174240.856127,177414.886989,180716.160136,184125.266756,189880.842647,194441.112331,199064.528089,203730.466618,208419.268018,215849.984669
4,0.084315,0.850095,1.520708,5.806775,16.448678,37.919793,56.711235,101.536730,139.807202,182.785925,...,6285.031400,6405.311708,6531.565459,6663.186200,6799.542440,7043.224353,7232.902565,7426.163485,7622.257361,7820.448834
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11705,0.141881,1.077012,5.238498,16.353338,39.966899,61.797936,114.351842,160.745432,258.660693,342.920984,...,10318.335044,10592.912639,10812.273077,11039.485146,11273.364036,11512.726013,11914.177828,12229.299833,12547.004446,12866.099310
11706,0.425642,3.231038,15.715493,49.060013,119.900698,185.393808,343.055527,482.236297,775.982079,1028.762953,...,30955.005132,31778.737915,32436.819231,33118.455435,33820.092105,34538.178036,35742.533481,36687.899497,37641.013338,38598.297927
11707,0.822208,7.696671,17.947672,69.222390,111.186200,266.213892,392.477909,746.916324,1034.833746,1713.048861,...,58069.698019,59116.896165,60222.689186,61382.446926,63624.771450,65347.288739,67121.249980,68940.042228,70796.953020,72685.380751
11708,0.425642,3.231038,15.715493,49.060013,119.900698,185.393808,343.055527,482.236297,775.982079,1028.762953,...,30955.005132,31778.737915,32436.819231,33118.455435,33820.092105,34538.178036,35742.533481,36687.899497,37641.013338,38598.297927
11709,0.349595,2.954631,14.184703,24.535991,63.492007,142.392653,211.673782,376.677945,517.635201,812.927307,...,25816.636129,26246.645047,27026.285486,27645.048305,28283.180249,28937.623370,29605.333976,30283.362370,31414.630691,32294.775682

In [114]:
result.to_csv("/content/result.csv")